set_intensity:
  name: Establecer Intensidad de Carga
  description: Establece la intensidad de carga del cargador V2C Trydan
  fields:
    intensity:
      name: Intensidad
      description: Intensidad de carga en amperios (entre 6 y 32)
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider

set_min_intensity:
  name: Establecer Intensidad Mínima
  description: Establece la intensidad mínima de carga del cargador V2C Trydan
  fields:
    min_intensity:
      name: Intensidad Mínima
      description: Intensidad mínima en amperios (entre 6 y 32)
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider

set_max_intensity:
  name: Establecer Intensidad Máxima
  description: Establece la intensidad máxima de carga del cargador V2C Trydan
  fields:
    max_intensity:
      name: Intensidad Máxima
      description: Intensidad máxima en amperios (entre 6 y 32)
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider

set_dynamic_power_mode:
  name: Establecer Modo de Potencia Dinámica
  description: Establece el modo de potencia dinámica del cargador V2C Trydan
  fields:
    DynamicPowerMode:
      name: Modo
      description: Modo de potencia dinámica (entre 0 y 5)
      required: true
      selector:
        select:
          options:
            - label: "Activar Potencia Temporizada"
              value: "0"
            - label: "Desactivar Potencia Temporizada"
              value: "1"
            - label: "Modo Exclusivo"
              value: "2"
            - label: "Modo Potencia Mínima"
              value: "3"
            - label: "Modo Red+FV"
              value: "4"
            - label: "Modo Parada"
              value: "5"