set_intensity:
  fields:
    intensity:
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: v2c_trydan

set_min_intensity:
  fields:
    min_intensity:
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: v2c_trydan

set_max_intensity:
  fields:
    max_intensity:
      required: true
      selector:
        number:
          min: 6
          max: 32
          step: 1
          unit_of_measurement: A
          mode: slider
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: v2c_trydan

set_dynamic_power_mode:
  fields:
    dynamic_power_mode:
      required: true
      selector:
        select:
          translation_key: dynamic_power_mode
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: v2c_trydan
